import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

console.log('wtf?')
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Society is crumbling but at least we can stream it</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Media reviews
        </h1>
        <h2>Watching movies while watching the world burn</h2>
        <div>
          Come, join me and watch some
          <Link href='/movies'>
             <a className={styles.inlineLink}>Movies</a>
          </Link>
        </div>
        <div>
          Or we can netflix and chill, binge watch some quality
          <Link href='/tv'>
             <a className={styles.inlineLink}>TV</a>
          </Link>
        </div>
        <div>
          If you really want to show off we can discuss
          <Link href='/books'>
             <a className={styles.inlineLink}>Literature</a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
